Printing numbers from 0 to the number given by the user
wojciechkostecki/precision-of-numbers pull request #2
Opened 2020-04-06 15:49 UTC by wojciechkostecki

Closes #1

2020-04-07 12:51 UTC, rbobko93 requested changes
You should be starting printing from 0 and you are not. You are printing starting with 0.1 or -0.1

2020-04-10 15:46 UTC, rbobko93 requested changes

2020-04-10 15:46 UTC, rbobko93 commented on src/Main.java
> +            while (x < number + 0.1) {
Why condition is x < number + 0.1 ? Why number + 0.1 ? Why you don't have number - 0.1 as well?

2020-04-10 15:46 UTC, rbobko93 commented on src/Main.java
> +            System.out.print(0 + " ");
Don't even try this solution with me. Remove it.

2020-04-10 22:41 UTC, rbobko93 commented on src/Main.java
> +            while (x < number + 0.1) {
@wojciechkostecki Why did you resolve this conversation without responding to it? You didn't change anything in the code.

2020-04-10 22:45 UTC, wojciechkostecki commented on src/Main.java
> +            while (x < number + 0.1) {
I added below -0.1.

2020-04-10 22:47 UTC, rbobko93 commented on src/Main.java
> +            while (x < number + 0.1) {
I know. I can see, but this answers only one of the questions.

2020-04-10 22:47 UTC, rbobko93 approved these changes

2020-04-10 22:50 UTC, merged